"use client"

import Head from "next/head"
import Image from "next/image"
import Link from "next/link"

export default function Home() {
  return (
    <>
      <Head>
        <title>Adnan Photos</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className="flex justify-center">
          <Link
            href="/upload"
            className="m-5 w-full rounded bg-pink-600 p-6 text-xl text-white "
          >
            Upload
          </Link>
        </div>
        <PhotosList />
      </main>
    </>
  )
}

const PhotosList = () => {
  const urls = [
    "https://cdn.statcdn.com/Infographic/images/normal/18819.jpeg",
    "https://cdn.statcdn.com/Infographic/images/normal/18819.jpeg",
    "https://cdn.statcdn.com/Infographic/images/normal/18819.jpeg",
    "https://cdn.statcdn.com/Infographic/images/normal/18819.jpeg",
    "https://cdn.statcdn.com/Infographic/images/normal/18819.jpeg",
    "https://cdn.statcdn.com/Infographic/images/normal/18819.jpeg",
    "https://cdn.statcdn.com/Infographic/images/normal/18819.jpeg",
  ]
  return (
    <>
      <ul>
        {urls.map((url) => (
          <li key={url}>
            <Image
              loader={() => url}
              src={url}
              alt="photo"
              width={500}
              height={500}
            />
          </li>
        ))}
      </ul>
    </>
  )
}
