"use client"

import Head from "next/head"
import Image from "next/image"
import Link from "next/link"
import { useEffect, useState } from "react"

export default function Home() {
  return (
    <>
      <Head>
        <title>Adnan Photos</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className="flex justify-center">
          <Link
            href="/upload"
            className="m-5 w-full rounded bg-pink-600 p-6 text-xl text-white "
          >
            Upload
          </Link>
        </div>
        <PhotosList />
      </main>
    </>
  )
}

const PhotosList = () => {
  const [urls, setUrls] = useState<string[]>([])

  const [isLoading, setIsLoading] = useState(true)

  const fetchPhotos = async () => {
    const ress = await fetch(process.env.NEXT_PUBLIC_BASE_URL + "/api/upload", {
      method: "GET",
    })

    if (ress.ok) {
      const data = await ress.json()
      setUrls(data)
    }

    setIsLoading(false)
  }

  useEffect(() => {
    fetchPhotos()
  })

  return (
    <>
      {isLoading && <p>Loading...</p>}
      {!isLoading && urls.length === 0 && <p>No photos found.</p>}
      {!isLoading && urls.length > 0 && (
        <>
          <ul>
            {urls.map((url) => (
              <li key={url}>
                <Image
                  loader={() => url}
                  src={url}
                  alt="photo"
                  width={500}
                  height={500}
                />
              </li>
            ))}
          </ul>
        </>
      )}
    </>
  )
}
